name: Network Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache boost and graph-tools installations
        uses: actions/cache@v2
        with:
          path: |
            /usr/include
            /usr/lib
          key: ${{ runner.os }}-boost-graph-tools-${{ hashFiles('**/*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-boost-graph-tools-

      - name: Install boost
        run: sudo apt install libboost-all-dev

      - name: Install graph tools
        run: conda install -c conda-forge -c ostrokach-forge -c pkgw-forge graph-tool
      
      - name: Install dependencies
        run: pip install -r dev_requirments.txt

      - name: Test with pytest
        run: pytest tests/networks